# Generated by Django 5.1.4 on 2024-12-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roadviolation',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
